FORMAT: 1A
HOST: iot-bath-vent-switch.herokuapp.com

# bath-vent-switch
bath-vent-switch is a simple api that allows user to turn on or off switch.
it doesn't matter in which state switch is, after calling on, it will be on,
adter calling off, it will be off.

# Ping [/ping]

## Ping service [GET]

Returns `200` if service is alive.

+ Response 200 (application/json)

## bath-vent turn on/off [/houses/{house_id}]
 
### get bath vent switch state [GET]
    
    checks state of bath vent switch in the house identified by house_id

    Status code is: 
        200 when everything was fine and successed;
        404 when house id specification is incorrect

+ response 200 (application/json) 

        {
            "houseid" : "a1bc00fb-4724-476a-a553-d65d2c1bac0e", 
            "status" : "on",
            "successed" : true
        }

+ response 503 (application/json) 

        {
            "houseid" : "a1bc00fb-4724-476a-a553-d65d2c1bac0e",
            "status" : "on",
            "successed" : false
        }

+ response 404 (application/json)

        {
            "houseid" : "a1bc00fb-4724-476a-a553-d65d2c1bac0e",
            "status" : null,
            "successed" : false
        }

### Change bath vent status [PUT]
        
    house is identified by house id, and json formatted arguments
    are passed in body. "set_status" is state in which bath vent need to move,
    timeout is interval, during of which, bath vent should keep this state, and 
    then be off.

    Status code is: 
        200 when everything was fine and successed;
        404 when device id specification is incorrect

+ Request (application/json)

        {
            "set_status": "on",
            "timeout": 30
        }
    
+ response 200 (application/json) 

        {
            "houseid" : "a1bc00fb-4724-476a-a553-d65d2c1bac0e",
            "status" : "on",
            "successed" : true
        }

+ response 404 (application/json) 

        {
            "houseid" : "a1bc00fb-4724-476a-a553-d65d2c1bac0e",
            "status" : null,
            "successed" : false
        }