FORMAT: 1A
HOST: iot-bath-vent-switch.herokuapp.com

# bath-vent-switch
bath-vent-switch is a simple api that allows user to turn on or off switch.
it doesn't matter in which state switch is, after calling on, it will be on,
adter calling off, it will be off.

# Ping [/ping]

## Ping service [GET]

Returns `200` if service is alive.

+ Response 200 (application/json)

## bath-vent turn on/off [/houses/{house_id}/action/{action_type}]
house is identified by houseid and bath_vent_switch is identified by 
as far as each house has only one bath vent switch.
Turns on or turns off bath vent depending on action_type.

    Status code is: 
        200 when everything was fine and successed;
        503 when device was not reached;
        404 when device id specification is incorrect

### turn on bath vent [PUT]

+ response 200 (application/json) 

        {
            "houseid" : "14",
            "status" : "on",
            "successed" : true
        }

+ response 503 (application/json) 

        {
            "houseid" : "14",
            "status" : "on",
            "successed" : false
        }

+ response 404 (application/json) 

        {
            "houseid" : "14",
            "status" : null,
            "successed" : false
        }
        

## bath-vent check state [/houses/{house_id}]
checks state of bath vent switch in the house identified by house_id

    Status code is: 
        200 when everything was fine and successed;
        503 when device was not reached, and in status, last gotten value
        is returned;
        404 when house id specification is incorrect

### get bath vent switch state [GET]

+ response 200 (application/json) 

        {
            "houseid" : "14", 
            "status" : "on",
            "successed" : true
        }

+ response 503 (application/json) 

        {
            "houseid" : "14", 
            "status" : "on",
            "successed" : false
        }

+ response 404 (application/json)

        {
            "houseid" : "14",
            "status" : null,
            "successed" : false
        }